test:
    resource: "@TestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

testAdev:
      path:      /testAdev
      defaults:  { _controller: AppBundle\Controller\TodosController::testAdevAction }
      methods:  [GET]