# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    app.todolistservice.transport: sendmail

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.todolistservice:
        class:        AppBundle\Controller\TodoList\TodoListService
        arguments: [ '@doctrine.orm.entity_manager', '@form.factory' ]
        # calls:
        #     - [setMyservice, ["@app.myservice"]]
        # arguments: ['%app.todolistservice.transport%']
        # arguments: ['@app.myservice']
#        arguments:    [sendmail]